function plot_posthoc(mfile,fname,vnames,rel,outdir)
%Plots posthoc analysis for all variables in anova.out file, or only those
%selected in the argument vnames.
%
%   INPUT ARGUMENTS
%       mfile  = mat file with data matrices generated by get_data family of fcns
%       fname  = text file generated by parse_stats.py after reading R out dirs.
%       vnames = cell array with names of selected variables. If empty, plots all.
%       rel    = whether to plot or not relative measures of selected variables
%       outdir = where to store created plots
%
%   OUTPUT ARGUMENTS
%       none

if nargin<5, outdir='out'; end
if nargin<4, rel=1; end
if nargin<3, vnames={'MTL','MTR','accQL','accQR','HarmonicityL','HarmonicityR','IPerfEfR','IPerfEfL','vfCircularityR','vfCircularityL','rho','minPeakDelay'};end
if nargin<2, fname='/home/jorge/Dropbox/anova.out'; end
%vnames={'HarmonicityR','HarmonicityL'};
%Create out dir if needed
if  ~isempty(outdir) && ~exist(outdir,'dir') 
    mkdir(outdir);
end

obj=load(mfile);
[dataB,dataU,varnamesB,varnamesU,vartypesB,vartypesU]=struct2vars(obj);
dataRel=get_data_rel(dataB,dataU,varnamesB,varnamesU, vartypesB);
flists = load_interactions(fname);
fvnames = cellfun(@(x) x(1),flists);

if isempty(vnames)
    %Plot all variables if vnames were not selected by user
    for v=1:length(flists)
        flist=flists{v};
        vname=flist{1};
        disp(['Analysis of variable ',vname])
        if length(flist)==1
            continue;
        elseif length(vname)>3 && strcmp(vname(1:3),'Uni')
            continue
        elseif length(vname)>3 && strcmp(vname(end-2:end),'rel')
            vname=vname(1:end-3);
            plot_posthoc_var(vname, dataRel, varnamesB,flist{2:end},1,outdir);
        else
            plot_posthoc_var(vname, dataB, varnamesB,flist{2:end},0,outdir);
        end
    end
else
    %Plot variables selected by user
    for v=1:length(vnames)
        vname=vnames{v};
        idx=strcmp(vname,fvnames);
        disp(['Analysis of variable ',vname])
        plot_posthoc_var(vname, dataB, varnamesB,flists{idx}{2},0,outdir)
        if rel
            idx=strcmp([vname,'rel'],fvnames);            
            if any(idx)
                disp(['Analysis of variable ',vname,'rel'])
                plot_posthoc_var(vname, dataRel, varnamesB,flists{idx}{2},rel,outdir);
            end
        end
    end
end
