function plot_posthoc(mfile,fname,vnames,rel,outdir,outfile)
%Plots posthoc analysis for all variables in anova.out file, or only those
%selected in the argument vnames.
%
%   INPUT ARGUMENTS
%       mfile  = mat file with data matrices generated by get_data family of fcns
%       fname  = text file generated by parse_stats.py after reading R out dirs.
%       vnames = cell array with names of selected variables. If empty, plots all.
%       rel    = whether to plot or not relative measures of selected variables
%       outdir = where to store created plots
%
%   OUTPUT ARGUMENTS
%       none
if nargin<6, outfile='kepasacontigo'; end
if nargin<5, outdir='out'; end
if nargin<4, rel=1; end
if nargin<3, vnames={'MTL','MTR','accQL','accQR','HarmonicityL','HarmonicityR','IPerfEfR','IPerfEfL','vfCircularityR','vfCircularityL','maxangleL','maxangleR','rho','minPeakDelay'};end
if nargin<2, fname='/home/jorge/Dropbox/WIP/last/anova.out'; end
%vnames={'minPeakDelayNorm'};

global ext;         ext='png';
global dpi;         dpi=300; 
global verbose;     verbose=1;
global fid
   
if isempty(outfile)
    fid=1;
else
    fid=fopen(outfile, 'w');
end

%Create out dir if needed
if  ~isempty(outdir) && ~exist(outdir,'dir') 
    mkdir(outdir);
end

obj=load(mfile);
flists = load_interactions(fname);
fvnames = cellfun(@(x) x(1),flists);

if isempty(vnames)
    %Plot all variables if vnames were not selected by user
    for v=1:length(flists)
        flist=flists{v};
        vname=flist{1};
        fprintf(fid,'Analysis of variable %s\n',vname);
        if length(flist)==1
            continue;
        elseif length(vname)>3 && strcmp(vname(1:3),'Uni')
            continue
        elseif length(vname)>3 && strcmp(vname(end-2:end),'rel')
            vname=vname(1:end-3);
            plot_posthoc_var(vname, obj.dataRel, obj.vnamesB,flist{2:end},1,outdir);
        elseif length(vname)>3 && strcmp(vname(1:4),'DID_')
            vname=vname(5:end);
            plot_posthoc_didvar(vname, obj.dataD, obj.vnamesB,flist{2:end},outdir);            
        else
            plot_posthoc_var(vname, obj.dataB, obj.vnamesB,flist{2:end},0,outdir);
        end
    end
else
    %Plot variables selected by user
    for v=1:length(vnames)
        vname=vnames{v};
        idx=strcmp(vname,fvnames);
        fprintf(fid,'Analysis of variable %s\n',vname);
        plot_posthoc_var(vname, obj.dataB, obj.vnamesB,flists{idx}{2},0,outdir)
        if rel
            idx=strcmp([vname,'rel'],fvnames);            
            if any(idx)
                fprintf(fid,'Analysis of variable %srel\n',vname);
                plot_posthoc_var(vname, obj.dataRel, obj.vnamesB,flists{idx}{2},rel,outdir);
            end
        end
    end
fclose(fid);    
end
