function [names, labels, ylims] = get_plots(obj)
    names = {...
            'Peak Velocity'...
            ,'Movement Time'...
            ,'Acceleration Time'...
            ,'Deceleration Time'...
            ,'Quotient -acc+acc'...
            ,'Index of Performance'...
            ,'Index of Performance Efective'...
            %,'Frequency'...
            %,'Frequency Quotient'...
            %,'Phase Difference'...
            };
    labels = {...
            'Peak velocity (m/s)'...
            ,'Movement Time (s)'...
            ,'Acceleration Time (s)'...
            ,'Deceleration Time (s)'...
            ,'Quocient decT/accT'...
            ,'IdxPerf (1/s)'...
            ,'IdxPerf Eff(1/s)'...
            %,'Frequency (Hz)'...
            %,'Frequency Quotient'...
            %,'Phase Difference (rad)'...
            };
    ylims = {...
             [0.4,1.0]...
             ,[1000,3000]...
             ,[400,1600]...
             ,[400,1600]...
             ,[0,2]...
             ,[0,10]...
             ,[0,10]...
             %,[0,3.5]...
             %,[0,5]...
             %,[-2*pi,2*pi]...
             };
end
